import EventsAction from "@/components/actions/events/EventsAction";
import OutputDirectory from "@/components/header/OutputDirectory";
import Routes from "@/components/header/Routes";
import DisplaySelectedImages from "@/components/header/SelectedImages";
import DisplayTimeline from "@/components/timeline/Timeline";
import { Grid } from "@mui/material";
import Head from "next/head";
import { useState } from "react";


export default function Home() {
  const [directoryName, setDirectoryName] = useState<string>("");
  const [selectedImages, setSelectedImages] = useState<Array<string>>([]);
  const [eventsParent, setEventsParent] = useState<any>();


  return (
    <>
      <Head>
        <title>Deltascope Desktop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-slate-600">
        <Grid container >
          <Grid item xs={12}>
              <div>
                <h1 className="text-3xl px-2 py-2 font-mono text-center" >Deltascope</h1>
              </div>          
          </Grid>
          <Grid item container>
            <OutputDirectory />
            <DisplaySelectedImages />
            <Routes />
          </Grid>
        </Grid>
        <Grid>
        <div>
          <DisplayTimeline eventsData={eventsParent} />
        </div>
        <div>
          <EventsAction images={[""]} directoryName={directoryName} setEventsParent={setEventsParent}  />
        </div>
      </Grid>
      </main>
    </>
  )
}
